#!/bin/sh

set -e

case "$1" in

  configure)
    cd /opt/atom/
    tar -xf atom*.tar.xz
    rm -rf atom*.tar.xz
    chown -R root:root /opt/atom
    if [ ! -e /usr/bin/apm ]; then
        ln -s /opt/atom/resources/app/apm/node_modules/.bin/apm /usr/bin/
    fi
    # Fixing missing libudev.so.0
    #if [ -n "`arch | grep 64`" ]; then
    #    if [ ! -e /lib/x86_64-linux-gnu/libudev.so.0 ]; then
    #        sudo ln -s /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0
    #    fi
    #else
    #    if [ ! -e /lib/i386-linux-gnu/libudev.so.0 ]; then
    #        sudo ln -s /lib/i386-linux-gnu/libudev.so.1 /lib/i386-linux-gnu/libudev.so.0
    #    fi
    #fi
    # Work-around Menu item not being created on first installation
    # Simlinks which cause issues with the package, recreate them here
    #if [ ! -e /opt/atom/resources/app/spec/fixtures/symlink-to-dir ]; then
    #    ln -s /opt/atom/resources/app/spec/fixtures/dir /opt/atom/resources/app/spec/fixtures/symlink-to-dir
    #fi
    #if [ ! -e /opt/atom/resources/app/spec/fixtures/symlink-to-file ]; then
    #    ln -s /opt/atom/resources/app/spec/fixtures/sample.js /opt/atom/resources/app/spec/fixtures/symlink-to-file
    #fi
    # Fix desktop file not showing up after first installation
    if [ -x /usr/bin/desktop-file-install ]; then
        desktop-file-install /usr/share/applications/atom.desktop > /dev/null 2>&1
    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

#DEBHELPER#

exit 0
